# Generated by Django 5.0.4 on 2024-12-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_invoice', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(max_length=30)),
                ('total_invoice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_invoice', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
