# Generated by Django 5.0.4 on 2024-11-05 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id_sale_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale_invoice',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sale_invoices', models.ForeignKey(db_column='fk_sale_invoice', on_delete=django.db.models.deletion.RESTRICT, related_name='sale_sale_invoice', to='sales.saleinvoice')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
    ]
