# Generated by Django 5.0.4 on 2024-11-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id_sale',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_invoices',
            field=models.ForeignKey(db_column='fk_sale_invoice', on_delete=django.db.models.deletion.RESTRICT, to='sales.saleinvoice'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='id_sale_invoice',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
