# Generated by Django 5.0.4 on 2024-12-14 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email_address_alter_client_phone_number_and_more'),
        ('sales', '0002_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='clients.client'),
        ),
    ]
