# Generated by Django 5.0.4 on 2024-11-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleinvoice_id_sale_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='id_sale_invoice',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
