# Generated by Django 5.0.4 on 2024-12-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_invoice_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_invoice',
            new_name='total',
        ),
    ]
