# Generated by Django 5.0.4 on 2024-11-05 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0004_alter_saleinvoice_id_sale_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='fk_product',
            field=models.ForeignKey(db_column='fk_product', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product'),
        ),
    ]
