# Generated by Django 5.0.4 on 2024-11-05 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0005_sale_fk_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='fk_product',
            field=models.ForeignKey(db_column='fk_product', on_delete=django.db.models.deletion.RESTRICT, to='inventory.product'),
        ),
    ]
