# Generated by Django 5.0.4 on 2024-11-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_fk_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sale',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='saleinvoice',
            table='sales_invoices',
        ),
    ]
