# Generated by Django 5.0.4 on 2024-06-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
