# Generated by Django 5.0.4 on 2024-08-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_stock_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_provider', models.CharField(max_length=50, unique=True)),
                ('nit_provider', models.CharField(max_length=15)),
                ('name_provider', models.CharField(max_length=100)),
                ('phone_provider', models.CharField(max_length=20)),
                ('address_provider', models.CharField(max_length=100)),
            ],
        ),
    ]
