# Generated by Django 5.0.4 on 2024-08-27 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='nit_provider',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_order', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.provider')),
            ],
        ),
    ]
