# Generated by Django 5.0.4 on 2024-11-05 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_category', models.CharField(max_length=20)),
                ('name_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_provider', models.CharField(max_length=50, unique=True)),
                ('nit_provider', models.CharField(max_length=15, unique=True)),
                ('name_provider', models.CharField(max_length=100)),
                ('phone_provider', models.CharField(max_length=20)),
                ('address_provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_product', models.CharField(max_length=50, unique=True)),
                ('name_product', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_product', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_product', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_order', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.provider')),
            ],
        ),
    ]
