# Generated by Django 5.0.4 on 2024-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_identification', models.CharField(max_length=4)),
                ('number_identification', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('second_last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_aux', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
